config/routes.rb
Rails.application.routes.draw do
  root 'audios#index'
  resources :audios
  get '/sync_repo/:id', to: 'audios#sync_repo', as: :sync_repo
  get '/stream/:id', to: 'audios#stream', as: :stream

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # NOTICE: we are leaving off the show because we'll just list htem all on a single page that will also serve as a form to create, update, and/or destroy settings
  resources :settings, except: [:show, :new, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio.rb
class Audio < ApplicationRecord
end

app/models/settings.rb
# RailsSettings Model
class Settings < RailsSettings::CachedSettings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  before_action :set_audio, only: [:show, :edit, :update, :destroy]

  # GET /audios
  # GET /audios.json
  def index
    @audios = Audio.all
    @repositories = Settings.repositories ||= []
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
  end

  # GET /audios/new
  def new
    @audio = Audio.new
  end

  # GET /audios/1/edit
  def edit
  end

  # POST /audios
  # POST /audios.json
  def create
    @audio = Audio.new(audio_params)

    respond_to do |format|
      if @audio.save
        format.html { redirect_to @audio, notice: 'Audio was successfully created.' }
        format.json { render :show, status: :created, location: @audio }
      else
        format.html { render :new }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audios/1
  # PATCH/PUT /audios/1.json
  def update
    respond_to do |format|
      if @audio.update(audio_params)
        format.html { redirect_to @audio, notice: 'Audio was successfully updated.' }
        format.json { render :show, status: :ok, location: @audio }
      else
        format.html { render :edit }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @audio.destroy
    respond_to do |format|
      format.html { redirect_to audios_url, notice: 'Audio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # we need a method to create database entries for the files in our Repositories. Edit the Audio controller and add this method
  def sync_repo
    repo = Settings.repositories[params[:id].to_i]

    files = `find #{repo} -name "*.mp3" -o -name "*.m4a" -o -name "*.ogg"`
    files = files.split("\n")

    files.each do |file|
      file_name = file.split('/')[-1]

      unless Audio.find_by_name(file_name)
        Audio.create(name: file_name, path: file)
      end
    end

    flash[:info] = 'Repository sync successful.'
    redirect_to audios_path
  end

  def stream
    audio = Audio.find(params[:id])
    if audio
      # sends w/e file you like to browse, usually zip and pdf, etc.
      send_file audio.path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio
      @audio = Audio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_params
      # params.fetch(:audio, {})
      params[:audio].permit(:name, :path)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def index
    @repositories = Settings.repositories ||= []
  end

  def create
    if Settings.repositories
      Settings.repositories = Settings.repositories << settings_params[:repositories][0]
    else
      Settings.repositories = settings_params[:repositories]
    end

    respond_to do |format|
      @repositories = Settings.repositories

      flash[:success] = 'Setting successfully saved.'
      format.html { redirect_to settings_path, success: 'Setting was successfully saved.' }
      format.json { render :index, status: :created, location: settings_path }
    end
  end

  def destroy
    puts "params: #{params}"
    if params[:id] == 'repositories'
      Settings.repositories.delete_at(params[:index].to_i)
      Settings.repositories = Settings.repositories
    end

    Settings.save
    @repositories = Settings.repositories

    respond_to do |format|
      flash[:success] = 'Setting successfully deleted.'
      format.html { redirect_to settings_path, success: 'Setting was successfully deleted.' }
      format.json { render :index, status: :created, location: settings_path }
    end
  end

  private

  def settings_params
    params.require(:settings).permit(repositories: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/views/audios/_form.html.erb
<br/><br/>

<%= form_for(@audio) do |f| %>
  <% if @audio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audio.errors.count, "error") %> prohibited this audio from being saved:</h2>

      <ul>
      <% @audio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="columns large-4">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-4">
      <%= f.text_field :path %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-4">
      <%= f.submit 'Save Audio File', class: 'button small success’ %>
    </div>
  </div>
<% end %>

<br/><br/>

app/views/audios/edit.html.erb
<h3>Editing <%= @audio.name %></h3>

<%= render 'form' %>

<%= link_to 'Show', @audio, class: 'button small' %> |
<%= link_to 'Back', audios_path, class: 'button small' %>

app/views/audios/index.html.erb
<h2>Audio Files</h2>

<% @repositories.each_with_index do |repo, idx| %>
  <h3>Repository:</h3>

  <%= repo %>

  <br/><hr><br/>

  <% if @audios.blank? %>
    No audio files created from this repository...
    <br/><br/>
  <% end %>
  <%= link_to 'Sync Repository', sync_repo_path(idx), class: 'button small' %>

  <br/><hr><br/>


  <ul>
    <% @audios.each do |audio| %>
      <li>
        <%= link_to audio.name, audio_path(audio) %>
      </li>
    <% end %>
  </ul>

<% end %>

app/views/audios/new.html.erb
<h2>New Audio</h2>

<%= render 'form' %>

<%= link_to 'Back', audios_path, class: 'button small' %>
#

app/views/audios/show.html.erb
<h2><%= @audio.name %></h2>

<br/><hr/><br/>

<audio id="<%= @audio.id %>" controls>
  <source src="<%= stream_path(@audio.id) %>"></source>
</audio>

<br/><hr/><br/>


<%= link_to 'Edit', edit_audio_path(@audio), class: 'button small' %> |
<%= link_to 'Back', audios_path, class: 'button small' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag :modernizr %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <% flash.each do |type, message| %>
      <div class="flash alert-box text-center <%= type %>", role="dialogalert", data-alert>
        <%= message %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>

    <div class="row">
      <div class="small-12">
        <br/><br/>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/settings/index.html.erb
<h3>Settings</h3>
<hr/>

<div class="row">
  <div class="columns large-6">
    <ul class="no-bullet">
      <li>
        <div class="row">
          <div class="columns large-4">
            <strong>repositories:</strong>
          </div>

          <div class="columns large-8">
            <ul class="repositories">
              <% @repositories.each_with_index do |repo, idx| %>
              <li>
                <%= repo %>
                &nbsp;&nbsp;&nbsp;&nbsp;

                <%= link_to 'Delete', '/settings/repositories?index=' + idx.to_s, method: 'delete' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

<hr />


<%= form_for 'settings' do %>
  <div class="row">
    <div class="columns large-4">
      <%= label_tag 'settings_repositories_', 'Add Repository' %>
      <%= text_field_tag 'settings[repositories][]', '', placeholder: 'Music Repository path' %>
    </div>
  </div>

  <div class="row">
    <div class="columns small-4">
      <%= submit_tag 'Save Settings', class: 'button small' %>
    </div>
  </div>
<% end %>